from __future__ import annotations
import rdkit.sping.PDF.pdfdoc
import typing

__all__ = [
    "A4",
    "AFMDIR",
    "AsyncGeneratorType",
    "BuiltinFunctionType",
    "BuiltinMethodType",
    "CellType",
    "ClassMethodDescriptorType",
    "CodeType",
    "CoroutineType",
    "DynamicClassAttribute",
    "FrameType",
    "FunctionType",
    "GeneratorType",
    "GetSetDescriptorType",
    "LINEEND",
    "LambdaType",
    "MakeFontDictionary",
    "MakeType1Fonts",
    "MappingProxyType",
    "MemberDescriptorType",
    "MethodDescriptorType",
    "MethodType",
    "MethodWrapperType",
    "ModuleType",
    "OutputGrabber",
    "PDFCatalog",
    "PDFDocument",
    "PDFError",
    "PDFImage",
    "PDFInfo",
    "PDFLiteral",
    "PDFObject",
    "PDFOutline",
    "PDFPage",
    "PDFPageCollection",
    "PDFStream",
    "PDFType1Font",
    "SimpleNamespace",
    "StandardEnglishFonts",
    "TestStream",
    "TracebackType",
    "WrapperDescriptorType",
    "bezierArc",
    "ceil",
    "coroutine",
    "cos",
    "new_class",
    "os",
    "pdfmetrics",
    "pdfutils",
    "pi",
    "prepare_class",
    "resolve_bases",
    "sin",
    "sys",
    "tempfile",
    "testOutputGrabber",
    "time",
    "zlib"
]


